Added missed locales support and romanian translation
qbcore-framework/qb-vehiclesales pull request #56
Opened 2022-08-24 14:29 UTC by wanderrer

**Describe Pull request**
Added missed locales support and romanian translation

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes

2022-08-24 14:31 UTC, tom-osborne commented
Just linting issues to fix please @wanderrer

2022-08-24 14:34 UTC, tom-osborne requested changes

2022-08-24 14:34 UTC, tom-osborne commented on locales/en.lua
>          no_space_on_lot = 'There is not space for your car on the lot!'
missing comma at end of line

2022-08-24 14:34 UTC, tom-osborne commented on locales/ro.lua
> +        no_space_on_lot = 'Din pacate, nu mai sunt spatii pentru a pune masina la vanzare!'
Missing comma at end of line

2022-08-24 14:34 UTC, tom-osborne commented on locales/ro.lua
> +
Remove whitespace

2022-08-26 07:43 UTC, wanderrer commented on locales/en.lua
>          no_space_on_lot = 'There is not space for your car on the lot!'
was added

2022-08-26 07:43 UTC, wanderrer commented on locales/ro.lua
> +        no_space_on_lot = 'Din pacate, nu mai sunt spatii pentru a pune masina la vanzare!'
was added

2022-08-26 07:45 UTC, wanderrer commented on locales/ro.lua
> +
was removed

2022-08-26 13:36 UTC, tom-osborne approved these changes

2022-08-26 13:37 UTC, tom-osborne approved these changes

2022-08-26 13:37 UTC, merged